name: Build Docker Image

on:
  push:
    tags:
      - v*
  workflow_dispatch: {}

jobs:
  build:
    uses: ./.github/workflows/build-docker-reusable.yml
    permissions:
      contents: read
      packages: write
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      tag_strategy: semver 