name: Build Docker Image - Dev Branch

on:
  push:
    branches: [ dev ]
  workflow_dispatch: {}

jobs:
  build:
    uses: ./.github/workflows/build-docker-reusable.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_tag: dev 